### ISSUE TITLE
Trouble while integrate with google calendar

### ISSUE THREAD

**Issue by YuriiKhomych** [odoo/documentation-user#232]
Hi, I found an issue that I got when I integrate with google calendar.
Please change:
This
![image](https://user-images.githubusercontent.com/26224789/28717664-65bad408-73ab-11e7-9b77-61568a42c2f6.png)
![image](https://user-images.githubusercontent.com/26224789/28721729-080127ae-73ba-11e7-9bda-1ce343f3826a.png)

To that
![image](https://user-images.githubusercontent.com/26224789/28717704-8e62468e-73ab-11e7-8277-9b174113dac0.png)
That work)

**Comment by tivisse** [comment]
@YuriiKhomych 

This change is not valid. If we set in the example 'mycompany.odoo.com', this is for a reason. It has to be defined with the domain name for the running instance so that the external service (here: Google) can redirect the users after authentification.

Replacing it by 'localhost:8069' won't fix it too. People testing this in a local instance have to use a localtunnel to make it work.

Thanks for the feedback. But unfortunately this change is wrong. 

Have a nice day,

Yannick.
